name: eventura
description: "Développement du projet tutoré."

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.7.0

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    supabase_flutter: ^2.8.3
    flutter_dotenv: ^5.1.0
    provider: ^6.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0
    test: ^1.25.7
    mockito: ^5.4.5
    build_runner: ^2.4.15
    mock_supabase_http_client: ^0.0.3+1

flutter:
    uses-material-design: true
    assets:
        - .env
