name: Eventura CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0' 
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze code (lint)
      run: flutter analyze

    - name: Run tests
      run: flutter test
